/**
 * Shared categories constants — single source of truth for category metadata.
 *
 * Category names are fetched dynamically from the database via `useCategories()`.
 * This file provides static icon, color, and description mappings for display.
 * Use `resolveCategoryMeta(name)` to look up metadata for any category name.
 *
 * For static fallback (before DB loads), use `FALLBACK_CATEGORIES`.
 */

import {
  Code,
  Palette,
  PenTool,
  Megaphone,
  Headphones,
  Calculator,
  Layout,
  ShieldCheck,
  Users,
  FolderKanban,
  BrainCircuit,
  MoreHorizontal,
  Brain,
  Shield,
  Link2,
  Video,
  Music2,
  Camera,
  Eye,
  FileText,
  Heart,
  Building2,
  Truck,
  Gamepad2,
  LineChart,
  FlaskConical,
  Wrench,
  CalendarCheck2,
  Plane,
  ShoppingCart,
  Share2,
  Leaf,
  Search,
  MessageSquare,
  Wand2,
  Network,
  Cpu,
  BarChart3,
  TrendingUp,
  Database,
  Tags,
  FileInput,
  Smartphone,
  Globe,
  Server,
  Layers,
  Settings2,
  Cloud,
  Wifi,
  TestTube,
  Bot,
  Image,
  Monitor,
  Mic,
  Languages,
  CheckCircle2,
  Mail,
  Phone,
  Table,
  GraduationCap,
  Package,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** All category names from DB (alphabetically sorted) */
export const FALLBACK_CATEGORIES = [
  'Admin & Operations',
  'AI & Machine Learning',
  'Android Development',
  'API Development',
  'AR / VR Development',
  'Architecture Design',
  'Artificial Intelligence Chatbots',
  'Audio Editing',
  'Automation Testing',
  'Backend Development',
  'Blockchain Development',
  'Bookkeeping',
  'Brand Identity Design',
  'Business Analysis',
  'Business Consulting',
  'CAD Design',
  'Career Coaching',
  'Cloud Computing',
  'Community Management',
  'Compliance Consulting',
  'Consulting & Strategy',
  'Content Management',
  'Content Marketing',
  'Content Writing',
  'Copywriting',
  'CRM Management',
  'Cross Platform Development',
  'Customer Experience & UX Research',
  'Customer Support',
  'Cybersecurity',
  'Data Analytics',
  'Data Annotation',
  'Data Engineering',
  'Data Entry',
  'Data Science',
  'Database Administration',
  'Deep Learning',
  'Design & Creative',
  'Development & IT',
  'DevOps Engineering',
  'Digital Marketing',
  'E-commerce Management',
  'Education & Training',
  'Email Marketing',
  'Engineering & Architecture',
  'Engineering Design',
  'ERP Development',
  'Event Planning',
  'Excel Automation',
  'Finance & Accounting',
  'Financial Analysis',
  'Financial Planning',
  'Flutter Development',
  'Frontend Development',
  'Full Stack Development',
  'Game Development',
  'Gaming & eSports',
  'Generative AI',
  'Ghostwriting',
  'Google Ads Management',
  'Graphic Design',
  'Health & Wellness',
  'HR & Recruitment',
  'HR Consulting',
  'Illustration',
  'Influencer Marketing',
  'Interior Design',
  'Investment Analysis',
  'iOS Development',
  'IT & Network Security',
  'IT Consulting',
  'Java Development',
  'Lead Generation',
  'Legal Consulting',
  'Legal Services',
  'Logo Design',
  'Machine Learning Engineering',
  'Marketing Automation',
  'Mechanical Design',
  'Meta Ads Management',
  'Mobile App Design',
  'Mobile App Development',
  'Motion Graphics',
  'Music & Audio',
  'Network Administration',
  'No-Code Development',
  'Online Tutoring',
  'Operations Management',
  'Payroll Management',
  'Performance Marketing',
  'Photography',
  'PPC Advertising',
  'Presentation Design',
  'Product Design',
  'Product Management',
  'Project Management',
  'Proofreading',
  'Python Development',
  'QA Testing',
  'React Development',
  'React Native Development',
  'Real Estate',
  'Recruitment Services',
  'Research Assistance',
  'Resume Writing',
  'Robotic Process Automation',
  'Sales & Customer Support',
  'Sales Consulting',
  'Science & Research',
  'Script Writing',
  'Search Engine Optimization',
  'SEM Management',
  'Shopify Development',
  'Social Media Management',
  'Social Media Marketing',
  'Software Architecture',
  'Software Development',
  'SQL Development',
  'Supply Chain & Logistics',
  'Sustainability & Green Tech',
  'Technical Support',
  'Technical Writing',
  'Telecalling',
  'Trademark Registration',
  'Trades & Services',
  'Translation Services',
  'Travel & Hospitality',
  'UI Design',
  'UI/UX Design',
  'User Research',
  'UX Writing',
  'Video & Animation',
  'Video Editing',
  'Virtual Assistance',
  'Voice Over Services',
  'Vue.js Development',
  'Web Design',
  'Web Development',
  'Webflow Development',
  'Website Maintenance',
  'WordPress Development',
  'Writing & Editing',
  'Writing & Translation',
  'YouTube Management',
] as const;

/** Service categories (includes "All" option) */
export const SERVICE_CATEGORIES = ['All', ...FALLBACK_CATEGORIES] as const;

/** Backward-compatible export */
export const CATEGORIES = FALLBACK_CATEGORIES;

/** Backward-compatible type export */
export type CategorySlug = (typeof FALLBACK_CATEGORIES)[number];
export type ServiceCategorySlug = (typeof SERVICE_CATEGORIES)[number];

/** Metadata for each category — icon, color, description. */
export interface CategoryMeta {
  icon: LucideIcon;
  color: string;
  bgColor: string;
  ringColor: string;
  description: string;
}

/**
 * Resolve category metadata by name.
 * Falls back to a default "Other" style for unknown categories.
 */
export function resolveCategoryMeta(name: string): CategoryMeta {
  return CATEGORY_META[name] ?? {
    icon: MoreHorizontal,
    color: 'text-slate-600',
    bgColor: 'bg-slate-100',
    ringColor: 'ring-slate-200',
    description: 'Other services and categories',
  };
}

/** Lookup map for category metadata keyed by category name (matches DB names). */
const CATEGORY_META: Record<string, CategoryMeta> = {
  'Admin & Operations': { icon: FolderKanban, color: 'text-slate-600', bgColor: 'bg-slate-100', ringColor: 'ring-slate-200', description: 'Business administration, operations management, and support' },
  'AI & Machine Learning': { icon: Brain, color: 'text-purple-600', bgColor: 'bg-purple-100', ringColor: 'ring-purple-200', description: 'AI models, ML pipelines, and predictive analytics' },
  'Android Development': { icon: Smartphone, color: 'text-green-600', bgColor: 'bg-green-100', ringColor: 'ring-green-200', description: 'Kotlin, Jetpack, and Android app development' },
  'API Development': { icon: Link2, color: 'text-sky-600', bgColor: 'bg-sky-100', ringColor: 'ring-sky-200', description: 'REST, GraphQL, and microservice API development' },
  'AR / VR Development': { icon: Eye, color: 'text-fuchsia-600', bgColor: 'bg-fuchsia-100', ringColor: 'ring-fuchsia-200', description: 'Augmented reality, virtual reality, and mixed reality' },
  'Architecture Design': { icon: Building2, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Architectural plans, building design, and structural engineering' },
  'Artificial Intelligence Chatbots': { icon: MessageSquare, color: 'text-violet-600', bgColor: 'bg-violet-100', ringColor: 'ring-violet-200', description: 'Conversational AI, chatbot development, and LLM integration' },
  'Audio Editing': { icon: Music2, color: 'text-rose-600', bgColor: 'bg-rose-100', ringColor: 'ring-rose-200', description: 'Audio cleanup, mixing, mastering, and post-production' },
  'Automation Testing': { icon: TestTube, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'Automated test scripts, frameworks, and QA automation' },
  'Backend Development': { icon: Server, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'Server-side logic, APIs, and backend infrastructure' },
  'Blockchain Development': { icon: Link2, color: 'text-orange-600', bgColor: 'bg-orange-100', ringColor: 'ring-orange-200', description: 'Smart contracts, DApps, and blockchain protocols' },
  'Bookkeeping': { icon: Calculator, color: 'text-emerald-600', bgColor: 'bg-emerald-100', ringColor: 'ring-emerald-200', description: 'Financial record keeping, reconciliations, and ledger management' },
  'Brand Identity Design': { icon: Palette, color: 'text-pink-600', bgColor: 'bg-pink-100', ringColor: 'ring-pink-200', description: 'Brand guidelines, logo systems, and identity creation' },
  'Business Analysis': { icon: LineChart, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Requirements gathering, process mapping, and needs analysis' },
  'Business Consulting': { icon: LineChart, color: 'text-emerald-600', bgColor: 'bg-emerald-100', ringColor: 'ring-emerald-200', description: 'Business strategy, management consulting, and growth advisory' },
  'CAD Design': { icon: Building2, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'AutoCAD, SolidWorks, and 3D CAD modeling' },
  'Career Coaching': { icon: TrendingUp, color: 'text-teal-600', bgColor: 'bg-teal-100', ringColor: 'ring-teal-200', description: 'Career development, interview prep, and professional mentoring' },
  'Cloud Computing': { icon: Cloud, color: 'text-sky-600', bgColor: 'bg-sky-100', ringColor: 'ring-sky-200', description: 'AWS, Azure, GCP cloud services, migration, and management' },
  'Community Management': { icon: Users, color: 'text-teal-600', bgColor: 'bg-teal-100', ringColor: 'ring-teal-200', description: 'Community building, moderation, and engagement strategies' },
  'Compliance Consulting': { icon: ShieldCheck, color: 'text-red-600', bgColor: 'bg-red-100', ringColor: 'ring-red-200', description: 'Regulatory compliance, GDPR, HIPAA, and industry standards' },
  'Consulting & Strategy': { icon: LineChart, color: 'text-emerald-600', bgColor: 'bg-emerald-100', ringColor: 'ring-emerald-200', description: 'Strategic planning, market analysis, and business transformation' },
  'Content Management': { icon: FileText, color: 'text-stone-600', bgColor: 'bg-stone-100', ringColor: 'ring-stone-200', description: 'CMS, content strategy, blogging, and editorial management' },
  'Content Marketing': { icon: FileText, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Content strategy, distribution, and lifecycle management' },
  'Content Writing': { icon: FileText, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Blog posts, articles, website content, and SEO writing' },
  'Copywriting': { icon: PenTool, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Sales copy, ad copy, email, and conversion-focused writing' },
  'CRM Management': { icon: Users, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'CRM setup, Salesforce, HubSpot, and customer relationships' },
  'Cross Platform Development': { icon: Smartphone, color: 'text-purple-600', bgColor: 'bg-purple-100', ringColor: 'ring-purple-200', description: 'Xamarin, .NET MAUI, Electron, and multi-platform development' },
  'Customer Experience & UX Research': { icon: Search, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'User research, usability testing, journey mapping, and service design' },
  'Customer Support': { icon: Headphones, color: 'text-teal-600', bgColor: 'bg-teal-100', ringColor: 'ring-teal-200', description: 'Email, chat, phone support, and help desk management' },
  'Cybersecurity': { icon: Shield, color: 'text-red-600', bgColor: 'bg-red-100', ringColor: 'ring-red-200', description: 'Security assessment, pentesting, and vulnerability analysis' },
  'Data Analytics': { icon: BarChart3, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Business intelligence, data visualization, and reporting' },
  'Data Annotation': { icon: Tags, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'Data labeling, image annotation, and dataset preparation' },
  'Data Engineering': { icon: Database, color: 'text-sky-600', bgColor: 'bg-sky-100', ringColor: 'ring-sky-200', description: 'Data pipelines, ETL, and warehouse architecture' },
  'Data Entry': { icon: FileInput, color: 'text-slate-600', bgColor: 'bg-slate-100', ringColor: 'ring-slate-200', description: 'Data entry, processing, and database management' },
  'Data Science': { icon: TrendingUp, color: 'text-purple-600', bgColor: 'bg-purple-100', ringColor: 'ring-purple-200', description: 'Statistical modeling, analysis, and insights generation' },
  'Database Administration': { icon: Database, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'Database management, optimization, backup, and recovery' },
  'Deep Learning': { icon: Network, color: 'text-violet-600', bgColor: 'bg-violet-100', ringColor: 'ring-violet-200', description: 'Neural networks, transformers, GANs, and advanced AI' },
  'Design & Creative': { icon: Palette, color: 'text-pink-600', bgColor: 'bg-pink-100', ringColor: 'ring-pink-200', description: 'UI/UX, graphic design, branding, and illustration' },
  'Development & IT': { icon: Code, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Web, mobile, backend, and full-stack development' },
  'DevOps Engineering': { icon: Settings2, color: 'text-orange-600', bgColor: 'bg-orange-100', ringColor: 'ring-orange-200', description: 'CI/CD, containerization, cloud infra, and automation' },
  'Digital Marketing': { icon: Megaphone, color: 'text-rose-600', bgColor: 'bg-rose-100', ringColor: 'ring-rose-200', description: 'SEO, social media, email, PPC, and content marketing' },
  'E-commerce Management': { icon: ShoppingCart, color: 'text-orange-600', bgColor: 'bg-orange-100', ringColor: 'ring-orange-200', description: 'Shopify, WooCommerce, Amazon FBA, and online stores' },
  'Education & Training': { icon: GraduationCap, color: 'text-orange-600', bgColor: 'bg-orange-100', ringColor: 'ring-orange-200', description: 'Tutoring, course creation, and career coaching' },
  'Email Marketing': { icon: Mail, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Email campaigns, newsletters, and email automation' },
  'Engineering & Architecture': { icon: Building2, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'CAD, civil, mechanical, electrical, and architectural' },
  'Engineering Design': { icon: Settings2, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'Mechanical, electrical, and civil engineering design' },
  'ERP Development': { icon: FolderKanban, color: 'text-violet-600', bgColor: 'bg-violet-100', ringColor: 'ring-violet-200', description: 'SAP, Odoo, Oracle ERP, and enterprise solutions' },
  'Event Planning': { icon: CalendarCheck2, color: 'text-pink-600', bgColor: 'bg-pink-100', ringColor: 'ring-pink-200', description: 'Weddings, corporate events, parties, and trade shows' },
  'Excel Automation': { icon: Table, color: 'text-green-600', bgColor: 'bg-green-100', ringColor: 'ring-green-200', description: 'Excel VBA, macros, automation, and complex formulas' },
  'Finance & Accounting': { icon: Calculator, color: 'text-emerald-600', bgColor: 'bg-emerald-100', ringColor: 'ring-emerald-200', description: 'Financial analysis, bookkeeping, and tax services' },
  'Financial Analysis': { icon: LineChart, color: 'text-emerald-600', bgColor: 'bg-emerald-100', ringColor: 'ring-emerald-200', description: 'Financial modeling, valuation, and investment research' },
  'Financial Planning': { icon: TrendingUp, color: 'text-emerald-600', bgColor: 'bg-emerald-100', ringColor: 'ring-emerald-200', description: 'Budgeting, forecasting, and wealth management' },
  'Flutter Development': { icon: Smartphone, color: 'text-sky-600', bgColor: 'bg-sky-100', ringColor: 'ring-sky-200', description: 'Cross-platform mobile apps using Flutter and Dart' },
  'Frontend Development': { icon: Layout, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'React, Vue, Angular, and modern frontend frameworks' },
  'Full Stack Development': { icon: Layers, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'End-to-end web and application development' },
  'Game Development': { icon: Gamepad2, color: 'text-violet-600', bgColor: 'bg-violet-100', ringColor: 'ring-violet-200', description: 'Unity, Unreal Engine, 2D/3D game development' },
  'Gaming & eSports': { icon: Gamepad2, color: 'text-violet-600', bgColor: 'bg-violet-100', ringColor: 'ring-violet-200', description: 'Esports, gaming content, and competitive gaming' },
  'Generative AI': { icon: Wand2, color: 'text-fuchsia-600', bgColor: 'bg-fuchsia-100', ringColor: 'ring-fuchsia-200', description: 'GenAI for text, image, audio, and video creation' },
  'Ghostwriting': { icon: PenTool, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Books, articles, and content written under another name' },
  'Google Ads Management': { icon: Search, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Google Ads setup, optimization, and ROI tracking' },
  'Graphic Design': { icon: Palette, color: 'text-pink-600', bgColor: 'bg-pink-100', ringColor: 'ring-pink-200', description: 'Print design, digital graphics, and visual content' },
  'Health & Wellness': { icon: Heart, color: 'text-pink-600', bgColor: 'bg-pink-100', ringColor: 'ring-pink-200', description: 'Fitness, nutrition, mental health, and medical' },
  'HR & Recruitment': { icon: Users, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'Talent acquisition, HR consulting, and recruitment' },
  'HR Consulting': { icon: Users, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'HR strategy, policy development, and org design' },
  'Illustration': { icon: Image, color: 'text-pink-600', bgColor: 'bg-pink-100', ringColor: 'ring-pink-200', description: 'Custom illustrations, vector art, and digital drawing' },
  'Influencer Marketing': { icon: Share2, color: 'text-rose-600', bgColor: 'bg-rose-100', ringColor: 'ring-rose-200', description: 'Influencer partnerships, campaign management, and outreach' },
  'Interior Design': { icon: Palette, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Interior space planning, decoration, and furniture design' },
  'Investment Analysis': { icon: TrendingUp, color: 'text-emerald-600', bgColor: 'bg-emerald-100', ringColor: 'ring-emerald-200', description: 'Investment research, portfolio analysis, and market analysis' },
  'iOS Development': { icon: Smartphone, color: 'text-slate-700', bgColor: 'bg-slate-200', ringColor: 'ring-slate-300', description: 'Swift, Objective-C, and iOS app development' },
  'IT & Network Security': { icon: Shield, color: 'text-red-600', bgColor: 'bg-red-100', ringColor: 'ring-red-200', description: 'Cybersecurity, cloud, networking, and system admin' },
  'IT Consulting': { icon: Headphones, color: 'text-slate-600', bgColor: 'bg-slate-100', ringColor: 'ring-slate-200', description: 'IT strategy, technology advisory, and transformation' },
  'Java Development': { icon: Code, color: 'text-orange-600', bgColor: 'bg-orange-100', ringColor: 'ring-orange-200', description: 'Java, Spring Boot, and enterprise application development' },
  'Lead Generation': { icon: Users, color: 'text-teal-600', bgColor: 'bg-teal-100', ringColor: 'ring-teal-200', description: 'B2B/B2C lead gen, prospecting, and list building' },
  'Legal Consulting': { icon: ShieldCheck, color: 'text-violet-600', bgColor: 'bg-violet-100', ringColor: 'ring-violet-200', description: 'Legal advice, contract review, and business law' },
  'Legal Services': { icon: ShieldCheck, color: 'text-violet-600', bgColor: 'bg-violet-100', ringColor: 'ring-violet-200', description: 'Contracts, legal research, compliance, and trademark' },
  'Logo Design': { icon: Palette, color: 'text-pink-600', bgColor: 'bg-pink-100', ringColor: 'ring-pink-200', description: 'Company logos, brand marks, and identity design' },
  'Machine Learning Engineering': { icon: Cpu, color: 'text-purple-600', bgColor: 'bg-purple-100', ringColor: 'ring-purple-200', description: 'ML pipelines, model deployment, and MLOps' },
  'Marketing Automation': { icon: Zap, color: 'text-orange-600', bgColor: 'bg-orange-100', ringColor: 'ring-orange-200', description: 'Marketing automation platforms, workflows, and nurturing' },
  'Mechanical Design': { icon: Settings2, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'Machine design, product engineering, and mechanical systems' },
  'Meta Ads Management': { icon: Search, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Facebook/Instagram ads, creative testing, and scaling' },
  'Mobile App Design': { icon: Smartphone, color: 'text-fuchsia-600', bgColor: 'bg-fuchsia-100', ringColor: 'ring-fuchsia-200', description: 'Mobile UI design, app prototypes, and mobile-first' },
  'Mobile App Development': { icon: Smartphone, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Native and cross-platform mobile app development' },
  'Motion Graphics': { icon: Video, color: 'text-fuchsia-600', bgColor: 'bg-fuchsia-100', ringColor: 'ring-fuchsia-200', description: 'Animated graphics, kinetic typography, and VFX' },
  'Music & Audio': { icon: Music2, color: 'text-rose-600', bgColor: 'bg-rose-100', ringColor: 'ring-rose-200', description: 'Music production, sound design, and audio branding' },
  'Network Administration': { icon: Wifi, color: 'text-sky-600', bgColor: 'bg-sky-100', ringColor: 'ring-sky-200', description: 'Network setup, configuration, and monitoring' },
  'No-Code Development': { icon: Zap, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Bubble, Webflow, Airtable, and no-code apps' },
  'Online Tutoring': { icon: GraduationCap, color: 'text-orange-600', bgColor: 'bg-orange-100', ringColor: 'ring-orange-200', description: 'One-on-one tutoring, academic support, and test prep' },
  'Operations Management': { icon: FolderKanban, color: 'text-slate-600', bgColor: 'bg-slate-100', ringColor: 'ring-slate-200', description: 'Business operations, process improvement, and workflows' },
  'Payroll Management': { icon: Calculator, color: 'text-emerald-600', bgColor: 'bg-emerald-100', ringColor: 'ring-emerald-200', description: 'Payroll processing, tax filing, and compensation' },
  'Performance Marketing': { icon: TrendingUp, color: 'text-rose-600', bgColor: 'bg-rose-100', ringColor: 'ring-rose-200', description: 'Data-driven marketing with measurable results' },
  'Photography': { icon: Camera, color: 'text-sky-600', bgColor: 'bg-sky-100', ringColor: 'ring-sky-200', description: 'Product, portrait, event photography, and editing' },
  'PPC Advertising': { icon: Search, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Pay-per-click campaigns across platforms' },
  'Presentation Design': { icon: Monitor, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'PowerPoint, Keynote, and presentation deck design' },
  'Product Design': { icon: Package, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'Product, industrial, and physical product design' },
  'Product Management': { icon: Package, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Product strategy, roadmapping, and lifecycle management' },
  'Project Management': { icon: FolderKanban, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Project planning, agile/scrum, and delivery management' },
  'Proofreading': { icon: CheckCircle2, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Grammar, spelling checks, and content polish' },
  'Python Development': { icon: Code, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Python scripting, Django/Flask, and automation' },
  'QA Testing': { icon: TestTube, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'Manual testing, bug tracking, and quality assurance' },
  'React Development': { icon: Code, color: 'text-sky-600', bgColor: 'bg-sky-100', ringColor: 'ring-sky-200', description: 'React.js, Next.js, and single-page applications' },
  'React Native Development': { icon: Smartphone, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Cross-platform mobile apps using React Native' },
  'Real Estate': { icon: Building2, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Property management, real estate marketing, valuation' },
  'Recruitment Services': { icon: Users, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'Executive search, talent sourcing, and screening' },
  'Research Assistance': { icon: Search, color: 'text-slate-600', bgColor: 'bg-slate-100', ringColor: 'ring-slate-200', description: 'Market research, academic research, and data collection' },
  'Resume Writing': { icon: FileText, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Professional resume, CV, and career document services' },
  'Robotic Process Automation': { icon: Bot, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'UiPath, Automation Anywhere, and RPA solutions' },
  'Sales & Customer Support': { icon: Headphones, color: 'text-teal-600', bgColor: 'bg-teal-100', ringColor: 'ring-teal-200', description: 'Sales, customer service, CRM, and support' },
  'Sales Consulting': { icon: TrendingUp, color: 'text-teal-600', bgColor: 'bg-teal-100', ringColor: 'ring-teal-200', description: 'Sales strategy, pipeline management, and optimization' },
  'Science & Research': { icon: FlaskConical, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'Scientific research, lab services, and academic writing' },
  'Script Writing': { icon: FileText, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Video scripts, screenplays, podcast, and dialogue' },
  'Search Engine Optimization': { icon: Search, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'On-page, off-page, technical SEO, and audits' },
  'SEM Management': { icon: Search, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Search engine marketing and bid management' },
  'Shopify Development': { icon: ShoppingCart, color: 'text-green-600', bgColor: 'bg-green-100', ringColor: 'ring-green-200', description: 'Shopify themes, apps, and store customization' },
  'Social Media Management': { icon: Share2, color: 'text-blue-500', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Social media account management and scheduling' },
  'Social Media Marketing': { icon: Share2, color: 'text-rose-600', bgColor: 'bg-rose-100', ringColor: 'ring-rose-200', description: 'Social media strategy, content, and paid social' },
  'Software Architecture': { icon: Building2, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'System design, architecture, and technical leadership' },
  'Software Development': { icon: Code, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Custom software, desktop apps, and enterprise solutions' },
  'SQL Development': { icon: Database, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'SQL queries, optimization, and database design' },
  'Supply Chain & Logistics': { icon: Truck, color: 'text-yellow-600', bgColor: 'bg-yellow-100', ringColor: 'ring-yellow-200', description: 'Inventory, procurement, shipping, and warehousing' },
  'Sustainability & Green Tech': { icon: Leaf, color: 'text-green-600', bgColor: 'bg-green-100', ringColor: 'ring-green-200', description: 'Environmental consulting, green energy, and ESG' },
  'Technical Support': { icon: Headphones, color: 'text-slate-600', bgColor: 'bg-slate-100', ringColor: 'ring-slate-200', description: 'Help desk, IT support, troubleshooting, and maintenance' },
  'Technical Writing': { icon: FileText, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Documentation, manuals, API docs, and guides' },
  'Telecalling': { icon: Phone, color: 'text-teal-600', bgColor: 'bg-teal-100', ringColor: 'ring-teal-200', description: 'Cold calling, telemarketing, and outbound sales' },
  'Trademark Registration': { icon: ShieldCheck, color: 'text-violet-600', bgColor: 'bg-violet-100', ringColor: 'ring-violet-200', description: 'Trademark search, filing, and IP protection' },
  'Trades & Services': { icon: Wrench, color: 'text-slate-700', bgColor: 'bg-slate-200', ringColor: 'ring-slate-300', description: 'Electrical, plumbing, carpentry, and contracting' },
  'Translation Services': { icon: Languages, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Document translation, localization, and interpretation' },
  'Travel & Hospitality': { icon: Plane, color: 'text-sky-600', bgColor: 'bg-sky-100', ringColor: 'ring-sky-200', description: 'Travel planning, hotel management, and tour guiding' },
  'UI Design': { icon: Layout, color: 'text-pink-600', bgColor: 'bg-pink-100', ringColor: 'ring-pink-200', description: 'User interface design, screen layouts, and design systems' },
  'UI/UX Design': { icon: Layout, color: 'text-pink-600', bgColor: 'bg-pink-100', ringColor: 'ring-pink-200', description: 'End-to-end UI/UX design and prototyping' },
  'User Research': { icon: Search, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'User interviews, surveys, usability testing, and personas' },
  'UX Writing': { icon: FileText, color: 'text-indigo-600', bgColor: 'bg-indigo-100', ringColor: 'ring-indigo-200', description: 'Microcopy, UI text, and content design for digital' },
  'Video & Animation': { icon: Video, color: 'text-fuchsia-600', bgColor: 'bg-fuchsia-100', ringColor: 'ring-fuchsia-200', description: '2D/3D animation, explainers, and animated content' },
  'Video Editing': { icon: Video, color: 'text-fuchsia-600', bgColor: 'bg-fuchsia-100', ringColor: 'ring-fuchsia-200', description: 'Post-production, editing, color grading, and compositing' },
  'Virtual Assistance': { icon: Headphones, color: 'text-teal-600', bgColor: 'bg-teal-100', ringColor: 'ring-teal-200', description: 'Admin support, calendar, email, and executive assistance' },
  'Voice Over Services': { icon: Mic, color: 'text-rose-600', bgColor: 'bg-rose-100', ringColor: 'ring-rose-200', description: 'Professional voice over, narration, and recording' },
  'Vue.js Development': { icon: Code, color: 'text-green-600', bgColor: 'bg-green-100', ringColor: 'ring-green-200', description: 'Vue.js, Nuxt.js, and component architecture' },
  'Web Design': { icon: Palette, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Website design, wireframing, and visual layout' },
  'Web Development': { icon: Globe, color: 'text-blue-600', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Websites, landing pages, and web applications' },
  'Webflow Development': { icon: Globe, color: 'text-blue-500', bgColor: 'bg-blue-100', ringColor: 'ring-blue-200', description: 'Webflow building, CMS design, and interactions' },
  'Website Maintenance': { icon: Wrench, color: 'text-slate-600', bgColor: 'bg-slate-100', ringColor: 'ring-slate-200', description: 'Updates, security, performance, and backups' },
  'WordPress Development': { icon: Globe, color: 'text-cyan-600', bgColor: 'bg-cyan-100', ringColor: 'ring-cyan-200', description: 'Themes, plugins, WooCommerce, and WordPress sites' },
  'Writing & Editing': { icon: PenTool, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'General writing, editing, and content refinement' },
  'Writing & Translation': { icon: PenTool, color: 'text-amber-600', bgColor: 'bg-amber-100', ringColor: 'ring-amber-200', description: 'Content, copywriting, translation, and editing' },
  'YouTube Management': { icon: Video, color: 'text-red-600', bgColor: 'bg-red-100', ringColor: 'ring-red-200', description: 'Channel management, content strategy, and growth' },
};
