-- ============================================================
-- MASTER CATEGORY ECOSYSTEM
-- Seeds all 117 categories with subcategories and skills
-- ============================================================

-- First, clear existing data (order matters due to FK constraints)
TRUNCATE TABLE skills CASCADE;
TRUNCATE TABLE subcategories CASCADE;
TRUNCATE TABLE categories CASCADE;

-- Ensure updated_at column exists on skills
ALTER TABLE skills ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- ============================================================
-- CATEGORY INSERT
-- All 117 categories from the master list
-- ============================================================

WITH inserted_categories AS (
  INSERT INTO categories (name, slug, icon, description, display_order, is_active)
  VALUES
    ('Development & IT', 'development-it', 'Code', 'Web, mobile, backend, and full-stack development services', 1, true),
    ('AI & Machine Learning', 'ai-machine-learning', 'Brain', 'Artificial intelligence, ML models, and predictive analytics', 2, true),
    ('Artificial Intelligence Chatbots', 'ai-chatbots', 'MessageSquare', 'Conversational AI, chatbot development, and LLM integration', 3, true),
    ('Generative AI', 'generative-ai', 'Wand2', 'Generative AI solutions including image, text, and code generation', 4, true),
    ('Deep Learning', 'deep-learning', 'Network', 'Neural networks, deep learning models, and advanced AI research', 5, true),
    ('Machine Learning Engineering', 'ml-engineering', 'Cpu', 'ML pipeline development, model deployment, and MLOps', 6, true),
    ('Data Science', 'data-science', 'BarChart3', 'Data analysis, statistical modeling, and insights generation', 7, true),
    ('Data Analytics', 'data-analytics', 'TrendingUp', 'Business intelligence, data visualization, and reporting', 8, true),
    ('Data Engineering', 'data-engineering', 'Database', 'Data pipelines, ETL processes, and data warehouse architecture', 9, true),
    ('Data Annotation', 'data-annotation', 'Tags', 'Data labeling, image annotation, and dataset preparation for ML', 10, true),
    ('Data Entry', 'data-entry', 'FileInput', 'Data entry, data processing, and database management', 11, true),
    ('Frontend Development', 'frontend-development', 'Layout', 'React, Vue, Angular, and modern frontend frameworks', 12, true),
    ('Backend Development', 'backend-development', 'Server', 'Server-side logic, APIs, and backend infrastructure', 13, true),
    ('Full Stack Development', 'full-stack-development', 'Layers', 'End-to-end web development across frontend and backend', 14, true),
    ('Mobile App Development', 'mobile-app-development', 'Smartphone', 'Native and cross-platform mobile application development', 15, true),
    ('iOS Development', 'ios-development', 'Apple', 'Swift, Objective-C, and iOS app development for iPhone/iPad', 16, true),
    ('Android Development', 'android-development', 'Smartphone', 'Kotlin, Java, and Android app development', 17, true),
    ('Flutter Development', 'flutter-development', 'Smartphone', 'Cross-platform mobile apps using Flutter and Dart', 18, true),
    ('React Native Development', 'react-native-development', 'Smartphone', 'Cross-platform mobile apps using React Native', 19, true),
    ('Cross Platform Development', 'cross-platform-dev', 'Smartphone', 'Multi-platform development using Xamarin, .NET MAUI, and others', 20, true),
    ('Web Development', 'web-development', 'Globe', 'Website development, landing pages, and web applications', 21, true),
    ('Web Design', 'web-design', 'Palette', 'Website design, wireframing, and visual layout creation', 22, true),
    ('React Development', 'react-development', 'Code', 'React.js component development and single-page applications', 23, true),
    ('Vue.js Development', 'vuejs-development', 'Code', 'Vue.js application development and component architecture', 24, true),
    ('Java Development', 'java-development', 'Code', 'Java application development, Spring Boot, and enterprise solutions', 25, true),
    ('Python Development', 'python-development', 'Code', 'Python scripting, web development with Django/Flask, and automation', 26, true),
    ('SQL Development', 'sql-development', 'Database', 'SQL query optimization, database design, and data modeling', 27, true),
    ('API Development', 'api-development', 'Link2', 'RESTful API, GraphQL, and microservice API development', 28, true),
    ('Software Development', 'software-development', 'Code', 'Custom software development, desktop apps, and enterprise solutions', 29, true),
    ('Software Architecture', 'software-architecture', 'Building2', 'System design, architecture planning, and technical leadership', 30, true),
    ('DevOps Engineering', 'devops-engineering', 'Settings2', 'CI/CD, containerization, cloud infrastructure, and automation', 31, true),
    ('Cloud Computing', 'cloud-computing', 'Cloud', 'AWS, Azure, GCP cloud services, migration, and management', 32, true),
    ('Cybersecurity', 'cybersecurity', 'Shield', 'Security assessment, penetration testing, and vulnerability analysis', 33, true),
    ('Network Administration', 'network-administration', 'Wifi', 'Network setup, configuration, monitoring, and troubleshooting', 34, true),
    ('Database Administration', 'database-administration', 'Database', 'Database management, optimization, backup, and recovery', 35, true),
    ('IT Consulting', 'it-consulting', 'Headphones', 'IT strategy, technology advisory, and digital transformation consulting', 36, true),
    ('Technical Support', 'technical-support', 'Headphones', 'Help desk, IT support, troubleshooting, and system maintenance', 37, true),
    ('Blockchain Development', 'blockchain-development', 'Link2', 'Smart contracts, DApps, and blockchain protocol development', 38, true),
    ('ERP Development', 'erp-development', 'FolderKanban', 'SAP, Oracle, Odoo, and enterprise resource planning solutions', 39, true),
    ('No-Code Development', 'no-code-development', 'Zap', 'Bubble, Webflow, Airtable, and no-code application building', 40, true),
    ('Webflow Development', 'webflow-development', 'Globe', 'Webflow site building, CMS design, and custom interactions', 41, true),
    ('Shopify Development', 'shopify-development', 'ShoppingCart', 'Shopify store development, theme customization, and app integration', 42, true),
    ('WordPress Development', 'wordpress-development', 'Globe', 'WordPress theme development, plugins, and site optimization', 43, true),
    ('Website Maintenance', 'website-maintenance', 'Wrench', 'Website updates, security patches, performance monitoring, and backups', 44, true),
    ('Game Development', 'game-development', 'Gamepad2', 'Unity, Unreal Engine, 2D/3D game development and game design', 45, true),
    ('AR / VR Development', 'ar-vr-development', 'Eye', 'Augmented reality, virtual reality, and mixed reality experiences', 46, true),
    ('Automation Testing', 'automation-testing', 'TestTube', 'Automated test scripts, test frameworks, and QA automation', 47, true),
    ('QA Testing', 'qa-testing', 'TestTube', 'Manual testing, bug tracking, test planning, and quality assurance', 48, true),
    ('Robotic Process Automation', 'rpa-automation', 'Bot', 'UiPath, Automation Anywhere, Blue Prism, and RPA solutions', 49, true),
    ('Design & Creative', 'design-creative', 'Palette', 'UI/UX, graphic design, branding, and creative services', 50, true),
    ('UI Design', 'ui-design', 'Layout', 'User interface design, screen layouts, and visual design systems', 51, true),
    ('UI/UX Design', 'ui-ux-design', 'Layout', 'End-to-end UI/UX design, prototyping, and user-centered design', 52, true),
    ('Mobile App Design', 'mobile-app-design', 'Smartphone', 'Mobile app UI design, app prototypes, and mobile-first design', 53, true),
    ('Product Design', 'product-design', 'Package', 'Product design, industrial design, and physical product development', 54, true),
    ('Graphic Design', 'graphic-design', 'Palette', 'Print design, digital graphics, banners, and visual content', 55, true),
    ('Brand Identity Design', 'brand-identity-design', 'Palette', 'Brand guidelines, logo systems, and complete brand identity creation', 56, true),
    ('Logo Design', 'logo-design', 'Palette', 'Company logos, brand marks, and visual identity design', 57, true),
    ('Illustration', 'illustration', 'Image', 'Custom illustrations, vector art, and digital drawing', 58, true),
    ('Presentation Design', 'presentation-design', 'Monitor', 'PowerPoint, Keynote, and presentation deck design services', 59, true),
    ('Motion Graphics', 'motion-graphics', 'Video', 'Animated graphics, kinetic typography, and visual effects', 60, true),
    ('Video Editing', 'video-editing', 'Video', 'Video post-production, editing, color grading, and compositing', 61, true),
    ('Video & Animation', 'video-animation', 'Video', '2D/3D animation, explainer videos, and animated content creation', 62, true),
    ('Audio Editing', 'audio-editing', 'Music2', 'Audio cleanup, mixing, mastering, and post-production', 63, true),
    ('Music & Audio', 'music-audio', 'Music2', 'Music production, sound design, composition, and audio branding', 64, true),
    ('Voice Over Services', 'voice-over-services', 'Mic', 'Professional voice over, narration, and audio recording services', 65, true),
    ('Photography', 'photography', 'Camera', 'Product photography, portrait, event, and commercial photography', 66, true),
    ('Writing & Translation', 'writing-translation', 'PenTool', 'Content writing, copywriting, translation, and editing services', 67, true),
    ('Content Writing', 'content-writing', 'FileText', 'Blog posts, articles, website content, and SEO writing', 68, true),
    ('Copywriting', 'copywriting', 'PenTool', 'Sales copy, ad copy, email copy, and conversion-focused writing', 69, true),
    ('Technical Writing', 'technical-writing', 'FileText', 'Documentation, user manuals, API docs, and technical guides', 70, true),
    ('Ghostwriting', 'ghostwriting', 'PenTool', 'Books, articles, and content written under another name', 71, true),
    ('Script Writing', 'script-writing', 'FileText', 'Video scripts, screenplays, podcast scripts, and dialogue writing', 72, true),
    ('UX Writing', 'ux-writing', 'FileText', 'Microcopy, user interface text, and content design for digital products', 73, true),
    ('Proofreading', 'proofreading', 'CheckCircle2', 'Grammar correction, spelling checks, and content polish', 74, true),
    ('Translation Services', 'translation-services', 'Languages', 'Document translation, localization, and interpretation services', 75, true),
    ('Resume Writing', 'resume-writing', 'FileText', 'Professional resume, CV writing, and career document services', 76, true),
    ('Writing & Editing', 'writing-editing', 'PenTool', 'General writing, editing, and content refinement services', 77, true),
    ('Digital Marketing', 'digital-marketing', 'Megaphone', 'SEO, social media, email, PPC, and content marketing services', 78, true),
    ('Search Engine Optimization', 'seo', 'Search', 'On-page SEO, off-page SEO, technical SEO, and SEO audits', 79, true),
    ('SEM Management', 'sem-management', 'Search', 'Search engine marketing, paid campaigns, and bid management', 80, true),
    ('Google Ads Management', 'google-ads-management', 'Search', 'Google Ads campaign setup, optimization, and ROI tracking', 81, true),
    ('Meta Ads Management', 'meta-ads-management', 'Search', 'Facebook and Instagram ad campaigns, creative testing, and scaling', 82, true),
    ('PPC Advertising', 'ppc-advertising', 'Search', 'Pay-per-click advertising across platforms and networks', 83, true),
    ('Performance Marketing', 'performance-marketing', 'TrendingUp', 'Data-driven marketing campaigns focused on measurable results', 84, true),
    ('Social Media Marketing', 'social-media-marketing', 'Share2', 'Social media strategy, content creation, and paid social', 85, true),
    ('Social Media Management', 'social-media-management', 'Share2', 'Social media account management, scheduling, and community engagement', 86, true),
    ('Community Management', 'community-management', 'Users', 'Online community building, moderation, and engagement strategies', 87, true),
    ('Influencer Marketing', 'influencer-marketing', 'Share2', 'Influencer partnerships, campaign management, and outreach', 88, true),
    ('Email Marketing', 'email-marketing', 'Mail', 'Email campaigns, newsletter management, and email automation', 89, true),
    ('Content Marketing', 'content-marketing', 'FileText', 'Content strategy, content distribution, and content lifecycle management', 90, true),
    ('Marketing Automation', 'marketing-automation', 'Zap', 'Marketing automation platforms, workflows, and lead nurturing', 91, true),
    ('Lead Generation', 'lead-generation', 'Users', 'B2B/B2C lead generation, prospecting, and list building', 92, true),
    ('Sales & Customer Support', 'sales-customer-support', 'Headphones', 'Sales, customer service, CRM, and support services', 93, true),
    ('Customer Support', 'customer-support', 'Headphones', 'Email support, live chat, phone support, and help desk management', 94, true),
    ('Telecalling', 'telecalling', 'Phone', 'Cold calling, telemarketing, appointment setting, and outbound sales', 95, true),
    ('CRM Management', 'crm-management', 'Users', 'CRM setup, Salesforce, HubSpot, and customer relationship management', 96, true),
    ('Sales Consulting', 'sales-consulting', 'TrendingUp', 'Sales strategy, pipeline management, and sales process optimization', 97, true),
    ('Virtual Assistance', 'virtual-assistance', 'Headphones', 'Administrative support, calendar management, and executive assistance', 98, true),
    ('Finance & Accounting', 'finance-accounting', 'Calculator', 'Bookkeeping, accounting, financial analysis, and tax services', 99, true),
    ('Bookkeeping', 'bookkeeping', 'Calculator', 'Financial record keeping, reconciliations, and ledger management', 100, true),
    ('Financial Analysis', 'financial-analysis', 'LineChart', 'Financial modeling, valuation, risk analysis, and investment research', 101, true),
    ('Financial Planning', 'financial-planning', 'LineChart', 'Financial planning, budgeting, forecasting, and wealth management', 102, true),
    ('Investment Analysis', 'investment-analysis', 'TrendingUp', 'Investment research, portfolio analysis, and market analysis', 103, true),
    ('Payroll Management', 'payroll-management', 'Calculator', 'Payroll processing, tax filing, and employee compensation management', 104, true),
    ('Excel Automation', 'excel-automation', 'Table', 'Excel VBA, macros, spreadsheet automation, and complex formulas', 105, true),
    ('Engineering & Architecture', 'engineering-architecture', 'Building2', 'CAD, mechanical, civil, electrical engineering, and architectural services', 106, true),
    ('CAD Design', 'cad-design', 'Building2', 'AutoCAD, SolidWorks, and 3D CAD modeling and drafting', 107, true),
    ('Engineering Design', 'engineering-design', 'Building2', 'Mechanical, electrical, and civil engineering design and analysis', 108, true),
    ('Mechanical Design', 'mechanical-design', 'Settings2', 'Machine design, product engineering, and mechanical systems', 109, true),
    ('Architecture Design', 'architecture-design', 'Building2', 'Architectural plans, building design, and structural engineering', 110, true),
    ('Interior Design', 'interior-design', 'Palette', 'Interior space planning, decoration, and furniture design', 111, true),
    ('Legal Services', 'legal-services', 'ShieldCheck', 'Contract law, legal research, compliance, and trademark services', 112, true),
    ('Legal Consulting', 'legal-consulting', 'ShieldCheck', 'Legal advice, contract review, and business law consultation', 113, true),
    ('Compliance Consulting', 'compliance-consulting', 'ShieldCheck', 'Regulatory compliance, GDPR, HIPAA, and industry standards', 114, true),
    ('Trademark Registration', 'trademark-registration', 'ShieldCheck', 'Trademark search, filing, and intellectual property protection', 115, true),
    ('HR & Recruitment', 'hr-recruitment', 'Users', 'Talent acquisition, HR consulting, and recruitment services', 116, true),
    ('HR Consulting', 'hr-consulting', 'Users', 'HR strategy, policy development, and organizational design', 117, true),
    ('Recruitment Services', 'recruitment-services', 'Users', 'Executive search, talent sourcing, and candidate screening', 118, true),
    ('Career Coaching', 'career-coaching', 'TrendingUp', 'Career development, interview prep, and professional mentoring', 119, true),
    ('Admin & Operations', 'admin-operations', 'FolderKanban', 'Business administration, operations management, and support', 120, true),
    ('Operations Management', 'operations-management', 'FolderKanban', 'Business operations, process improvement, and workflow optimization', 121, true),
    ('Project Management', 'project-management', 'FolderKanban', 'Project planning, agile/scrum, and project delivery management', 122, true),
    ('Product Management', 'product-management', 'Package', 'Product strategy, roadmapping, and product lifecycle management', 123, true),
    ('Business Analysis', 'business-analysis', 'LineChart', 'Requirements gathering, process mapping, and business needs analysis', 124, true),
    ('Research Assistance', 'research-assistance', 'Search', 'Market research, academic research, and data collection support', 125, true),
    ('Education & Training', 'education-training', 'GraduationCap', 'Online tutoring, course creation, and educational content', 126, true),
    ('Online Tutoring', 'online-tutoring', 'GraduationCap', 'One-on-one tutoring, academic support, and test prep services', 127, true),
    ('Business Consulting', 'business-consulting', 'LineChart', 'Business strategy, management consulting, and growth advisory', 128, true),
    ('Consulting & Strategy', 'consulting-strategy', 'LineChart', 'Strategic planning, market analysis, and business transformation', 129, true),
    ('E-commerce Management', 'ecommerce-management', 'ShoppingCart', 'Online store management, marketplace operations, and product listings', 130, true),
    ('YouTube Management', 'youtube-management', 'Video', 'YouTube channel management, content strategy, and growth optimization', 131, true),
    ('Science & Research', 'science-research', 'FlaskConical', 'Scientific research, lab services, and academic writing', 132, true),
    ('Health & Wellness', 'health-wellness', 'Heart', 'Healthcare, fitness, nutrition, and wellness services', 133, true),
    ('Real Estate', 'real-estate', 'Building2', 'Property management, real estate marketing, and valuation', 134, true),
    ('Supply Chain & Logistics', 'supply-chain-logistics', 'Truck', 'Inventory, procurement, shipping, and warehouse operations', 135, true),
    ('Gaming & eSports', 'gaming-esports', 'Gamepad2', 'Game development, esports management, and gaming content', 136, true),
    ('Sustainability & Green Tech', 'sustainability-green-tech', 'Leaf', 'Environmental consulting, green energy, and ESG reporting', 137, true),
    ('Customer Experience & UX Research', 'customer-experience-ux-research', 'Search', 'User research, usability testing, journey mapping, and service design', 138, true),
    ('User Research', 'user-research', 'Search', 'User interviews, surveys, usability testing, and persona development', 139, true),
    ('Trades & Services', 'trades-services', 'Wrench', 'Electrical, plumbing, carpentry, HVAC, and contracting services', 140, true),
    ('Event Planning', 'event-planning', 'CalendarCheck2', 'Weddings, corporate events, parties, and trade show planning', 141, true),
    ('Travel & Hospitality', 'travel-hospitality', 'Plane', 'Travel planning, hotel management, tour guiding, and culinary', 142, true),
    ('Content Management', 'content-management', 'FileText', 'CMS management, content strategy, and editorial operations', 143, true)
  RETURNING id, name, slug
)
SELECT * FROM inserted_categories;
