// ═══════════════════════════════════════════════════════════════════
// Vercel Serverless Function — Vike SSR Handler
// ═══════════════════════════════════════════════════════════════════
// This function runs on Vercel's Node.js runtime and handles all
// incoming requests through Vike's server-side rendering pipeline.
//
// The build output (dist/server/entry.mjs) is generated by Vike's
// vite build and contains the pre-compiled server entry.
// ═══════════════════════════════════════════════════════════════════

import { renderPage } from 'vike/server';

/** @type {import('@vercel/node').VercelRequest} */
/** @type {import('@vercel/node').VercelResponse} */

export default async function handler(req, res) {
  const { url } = req;

  // ─── Serve static assets directly (no SSR needed) ─────
  // Vercel automatically serves static files from the output directory.
  // This function only handles routes that need SSR.

  try {
    // ─── Render the page via Vike SSR ─────────────────────
    const pageContext = await renderPage({
      urlOriginal: url,
    });

    const { httpResponse } = pageContext;

    if (!httpResponse) {
      // Vike didn't find a matching page — fall back to 200 empty
      res.status(200).send('');
      return;
    }

    const { body, statusCode, contentType } = httpResponse;

    // ─── Early Hints (103) for performance ────────────────
    const earlyHints = /** @type {string[] | undefined} */ (
      httpResponse.earlyHints?.map((h) => h.link)
    );
    if (res.writeEarlyHints && earlyHints && earlyHints.length > 0) {
      res.writeEarlyHints({ link: earlyHints });
    }

    // ─── Send the SSR response ───────────────────────────
    res.status(statusCode);
    if (contentType) {
      res.setHeader('Content-Type', contentType);
    }
    res.send(body);
  } catch (err) {
    console.error('[Vike SSR] Error rendering page:', err);
    // Fallback: let Vercel serve the static fallback (index.html)
    res.status(500).send(`
      <!DOCTYPE html>
      <html>
        <head><title>Error - Growlancer</title></head>
        <body>
          <h1>Server Error</h1>
          <p>Please try again later.</p>
        </body>
      </html>
    `);
  }
}
